### ISSUE TITLE
getCandles listener never gets triggered

### ISSUE THREAD

**Issue by solarfrantz** [peterszombati/xapi-node#16] opened 2021-04-24 09:23 UTC
I've tried to get the realtime candles, even waited more the one minute as the official docs says and apparently the listener never gets called, see the code from below:

```
const x = new XAPI.default({
    accountId: <MY-ACCOUNT-ID>,
    password: <MY-PASSWORD>,
    type: 'demo' // or demo
});

x.connect();

x.onReady(async () => {
    console.log('Connection is ready');

    x.Stream.listen.getCandles((data) => {
        // THIS IS NEVER REACHED
        console.log("GOT DATA", data);
    });

    x.Stream.subscribe.getCandles('BITCOIN')
        .catch(() => { console.error('subscribe for BITCOIN failed')});

})
```

Am I doing something wrong ?

PS: getTickPrices works as expected

**Comment by peterszombati** [comment] 2021-04-25 07:49
Hi @solarfrantz 
I found the bug,
its caused by xOpenHub server logic.

for quick fix you have to do this request before subscribe for candles
```ts
x.getPriceHistory({
  symbol: 'BITCOIN',
  period: PERIOD_FIELD.PERIOD_M1,
  ticks: -1
})
``` 
I close this ticket and create another one

**Closed by peterszombati** 2021-04-25 07:49 UTC

**Comment by peterszombati** [comment] 2021-04-25 07:58
https://github.com/peterszombati/xapi-node/issues/17

**Comment by peterszombati** [comment] 2021-04-25 07:59
I created the new issue related to this: https://github.com/peterszombati/xapi-node/issues/17

**Comment by peterszombati** [comment] 2021-04-25 08:00
I created a new issue related to this: https://github.com/peterszombati/xapi-node/issues/17

**Comment by solarfrantz** [comment] 2021-04-25 09:15
That's very odd, have you tried also submitting a bug on their API's, maybe they'll fix it and we won't have to do this ugly workaround ?
